# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gil < Formula
  desc "Insert locale data into your locales directory"
  homepage "https://github.com/AlejandroSuero/go-insert-locale"
  version "0.0.4"
  license "MIT"

  on_macos do
    url "https://github.com/AlejandroSuero/go-insert-locale/releases/download/v0.0.4/gil_0.0.4_darwin_all.tar.gz"
    sha256 "566f6e371bb3244794a41817be4075ac72bb7de91d90ebf4913f4e3456372325"

    def install
      bin.install "go-insert-locale"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlejandroSuero/go-insert-locale/releases/download/v0.0.4/gil_0.0.4_linux_amd64.tar.gz"
        sha256 "4c0e8c18bf59f0a3d9a88989962968ae53a257932f2480dfa91a513c956a71b6"

        def install
          bin.install "gil"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlejandroSuero/go-insert-locale/releases/download/v0.0.4/gil_0.0.4_linux_arm64.tar.gz"
        sha256 "5084546499a920cdc53e56a5f2693ada4204b53b0d61a6833fb0f7a08617c93c"

        def install
          bin.install "gil"
        end
      end
    end
  end
end
